package emanondev.quests.task;

import java.util.Arrays;
import java.util.List;

import org.bukkit.Material;

import emanondev.quests.Defaults;
import emanondev.quests.configuration.ConfigSection;
import emanondev.quests.mission.Mission;
import emanondev.quests.player.QuestPlayer;
import emanondev.quests.utils.YmlLoadable;

import net.md_5.bungee.api.ChatColor;
import net.md_5.bungee.api.chat.BaseComponent;
import net.md_5.bungee.api.chat.ComponentBuilder;

public class VoidTaskType extends TaskType {
	public VoidTaskType() {
		super("ERROR");
	}
	
	@Override
	public Task getTaskInstance(ConfigSection m, Mission parent) {
		return new VoidTask(m,parent);
	}

	public class VoidTask extends YmlLoadable implements Task {
		private final static String name = "Void Task";
		private final Mission parent;
		private final String taskID;
		
		public VoidTask(ConfigSection m,Mission parent) {
			super(m);
			this.parent = parent;
			this.taskID = loadName(m).toLowerCase();
		}
		private String loadName(ConfigSection m) {
			String name = m.getName();
			if (name==null||name.isEmpty())
				throw new NullPointerException();
			return name;
		}
		@Override
		public String getNameID() {
			return taskID;
		}
	
		@Override
		public Mission getParent() {
			return parent;
		}
	
		@Override
		public TaskType getTaskType() {
			return VoidTaskType.this;
		}
		
		@Override
		public String getDisplayName() {	return name;	}
		@Override
		public int getMaxProgress() {	return 1;	}
		@Override
		public String getUnstartedDescription() {	return name;	}
		@Override
		public String getProgressDescription() {	return name;	}
		@Override
		public boolean onProgress(QuestPlayer p) {	return false;	}
		@Override
		public boolean onProgress(QuestPlayer p, int amount) {	return false;	}
		private boolean dirty = false;
		@Override
		public boolean isDirty() { return dirty;	}
		@Override
		public void setDirty(boolean value) { 
			dirty = value;
			if (dirty==true)
				parent.setDirty(true);
		}
		@Override
		public BaseComponent[] toComponent() {
			return new ComponentBuilder(ChatColor.RED+"Generated by an Error on the config").create();
		}
		
		protected  List<String> getWorldsListDefault(){
			return Defaults.TaskDef.getWorldsListDefault();
		}
		protected boolean shouldWorldsAutogen() {
			return Defaults.TaskDef.shouldWorldsAutogen();
		}
		protected boolean getUseWorldsAsBlacklistDefault() {
			return Defaults.TaskDef.getUseWorldsAsBlacklistDefault();
		}
		@Override
		protected boolean shouldAutogenDisplayName() {
			return Defaults.TaskDef.shouldAutogenDisplayName();
		}
	}

	@Override
	public Material getGuiItemMaterial() {
		return Material.BARRIER;
	}

	private static final List<String> description = Arrays.asList(
			"&7Task generated by an error"
			);
	@Override
	public List<String> getDescription() {
		return description;
	}
}
