#
#   this file stores information for default values when creating quests missions....
#   when quests.yml do not define a value for something the plugin attemps to read the value from this file
#
#   when autogenerate flags is set to true allows to force automatically generate configuration on quest when flagged item is not specified
#


#should gui items be unbreakable when not specified?
#this is usefull for custom texturepack using damage
gui:
    unbreakable-items: 
        default-value: true
#default quests configurations
quest:
    #prefix for quest display name
    display-name-prefix:
        #prefix value
        default-value: ""
        
        
    #allows to prevent quest progress on a specified world list
    disabled-world:
        #automatically generate disabled-world values for each quest on quest.yml ?
        autogenerate: false
        #use this list as a blacklist? (empty list will be always flagged as blacklist)
        use-as-blacklist: true
        #worlds of the list
        worlds: []
        
        
    #quest may be repeated once completed with a cooldown
    cooldown:
        #automatically generate cooldown values for each quest on quest.yml ?
        autogenerate: true
        #default: minutes to wait to repeat a quest (never set below 0)
        minutes: 1440
        #default: quest may be repated?
        enable: false
        
    display:
        #when player do not satisfy requires for the quest
        LOCKED:
            #quests gui items may be hided from gui on some state of the quest
            hide:
                #automatically generate hide.locked values for each quest on quest.yml ?
                autogenerate: false
                #default value
                value: false
            item:
                autogenerate: false
                #format is Material:data:damage:unbreakable (on 1.13+ format will be Material:damage:unbreakable)
                #ex: DIAMOND_SWORD:0:100:true (DIAMOND_SWORD:100:true)
                #data and damage default values when not specified are both 0
                value: "STAINED_GLASS_PANE:14"
            desc:
                autogenerate: false
                value: 
                - "&4&l&m---&8&l&m[--&8     * &4{quest-name}&8 *     &l&m--]&4&l&m---"
                - ""
                - "&7➤ Quest Locked"
                - ""
                - "&4&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&4&l&m---"
        #when player meets requires to start a quest
        UNSTARTED:
            hide:
                autogenerate: false
                #this specific value should never be set to true
                value: false
            item:
                autogenerate: false
                value: "BOOK"
            desc:
                autogenerate: false
                value: 
                - "&9&l&m---&8&l&m[--&8     * &9{quest-name}&8 *     &l&m--]&9&l&m---"
                - ""
                - "&7➤ Missions: &e{completed-mission-amount}&9/{mission-amount}"
                - ""
                - "&9&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&9&l&m---"
        #when player has started the quest
        ONPROGRESS:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "BOOK"
            desc:
                autogenerate: false
                value: 
                - "&9&l&m---&8&l&m[--&8     * &9{quest-name}&8 *     &l&m--]&9&l&m---"
                - ""
                - "&7➤ Missions: &e{completed-mission-amount}&9/{mission-amount}"
                - ""
                - "&9&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&9&l&m---"
        #when player has completed the quest but it"s still waiting to unlock it again
        COOLDOWN:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:1"
            desc:
                autogenerate: false
                value: 
                - "&6&l&m---&8&l&m[--&8     * &6{quest-name}&8 *     &l&m--]&6&l&m---"
                - ""
                - "&7➤ Quest On Cooldown for {quest-cooldownleft}"
                - ""
                - "&6&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&6&l&m---"
        #when player has completed and cannot do it again (cooldown = false)
        COMPLETED:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:5"
            desc:
                autogenerate: false
                value: 
                - "&2&l&m---&8&l&m[--&8     * &2{quest-name}&8 *     &l&m--]&2&l&m---"
                - ""
                - "&2➤ Quest Completed"
                - ""
                - "&2&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&2&l&m---"
        #when player has failed and cannot do it again (cooldown = false)
        FAILED:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:15"
            desc:
                autogenerate: false
                value:
                - "&4&l&m---&8&l&m[--&8     * &4{quest-name}&8 *     &l&m--]&4&l&m---"
                - ""
                - "&7➤ Quest Failed!"
                - ""
                - "&4&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&4&l&m---"
    display-name:
        autogenerate: true
#default missions configurations
mission:
    #prefix for mission display name
    display-name-prefix:
        #prefix value
        default-value: ""
    #allows to prevent mission progress on a specified world list
    disabled-world:
        #automatically generate this value for each quest on quest.yml ?
        autogenerate: false
        #use this list as a blacklist? (empty list will be always flagged as blacklist)
        use-as-blacklist: true
        #worlds of the list
        worlds: []
    cooldown:
        autogenerate: true
        minutes: 1440
        enable: false
        
    display:
        #when player do not satisfy requires for the mission
        LOCKED:
            #quests gui items may be hided from gui on some state of the mission
            hide:
                #automatically generate hide.locked values for each mission on quests.yml ?
                autogenerate: false
                #default value
                value: false
            item:
                autogenerate: false
                #format is Material:data:damage:unbreakable (on 1.13+ format will be Material:damage:unbreakable)
                #ex: DIAMOND_SWORD:0:100:true (DIAMOND_SWORD:100:true)
                #data and damage default values when not specified are both 0
                value: "STAINED_GLASS_PANE:14"
            desc:
                autogenerate: false
                value: 
                - "&4&l&m---&8&l&m[--&8     * &4{mission-name}&8 *     &l&m--]&4&l&m---"
                - ""
                - "&7➤ Mission Locked"
                - ""
                - "&4&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&4&l&m---"
        #when player meets requires to start a mission
        UNSTARTED:
            hide:
                autogenerate: false
                #this specific value should never be set to true
                value: false
            item:
                autogenerate: false
                value: "PAPER"
            desc:
                autogenerate: false
                value: 
                - "&9&l&m---&8&l&m[--&8     * &9{mission-name}&8 *     &l&m--]&9&l&m---"
                - ""
                - "{foreach-task}&7➤ {<task>-unstarted-description}"
                - ""
                - "&9&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&9&l&m---"
        #when player has started the mission
        ONPROGRESS:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "MAP"
            desc:
                autogenerate: false 
                value: 
                - "&9&l&m---&8&l&m[--&8     * &9{mission-name}&8 *     &l&m--]&9&l&m---"
                - ""
                - "{foreach-task}&7➤ {<task>-progress-description}"
                - ""
                - "&9&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&9&l&m---"
        #when player has completed the mission but it"s still waiting to unlock it again
        COOLDOWN:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:1"
            desc:
                autogenerate: false
                value: 
                - "&6&l&m---&8&l&m[--&8     * &6{mission-name}&8 *     &l&m--]&6&l&m---"
                - ""
                - "&7➤ Mission On Cooldown for {mission-cooldownleft}"
                - ""
                - "&6&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&6&l&m---"
        #when player has completed and cannot do it again (cooldown = false)
        COMPLETED:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:5"
            desc:
                autogenerate: false
                value: 
                - "&2&l&m---&8&l&m[--&8     * &2{mission-name}&8 *     &l&m--]&2&l&m---"
                - ""
                - "&2➤ Mission Completed"
                - ""
                - "&2&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&2&l&m---"
        #when player has failed and cannot do it again (cooldown = false)
        FAILED:
            hide:
                autogenerate: false
                value: false
            item:
                autogenerate: false
                value: "STAINED_GLASS_PANE:15"
            desc:
                autogenerate: false
                value:
                - "&4&l&m---&8&l&m[--&8     * &4{mission-name}&8 *     &l&m--]&4&l&m---"
                - ""
                - "&7➤ Mission Failed!"
                - ""
                - "&4&l&m---&8&l&m[--&8            &m*---------*&8            &l&m--]&4&l&m---"
    
    display-name:
        autogenerate: true
        
    start-text:
    - "&aMission &l{mission-name} &a➤ Started!"
    complete-text:
    - "&aMission &l{mission-name} &a➤ Completed!"
    fail-text:
    - "&cMission &l{mission-name} &c➤ Failed!"
    unpaused-text:
    - "&eMission &l{mission-name} &e➤ Reactivated!"
    paused-text:
    - "&eMission &l{mission-name} &e➤ Paused!"
    
task:
    #prefix for task display name
    display-name-prefix:
        #prefix value
        default-value: ""
    #allows to prevent mission progress on a specified world list
    disabled-world:
        #automatically generate this value for each task on quest.yml ?
        autogenerate: false
        #use this list as a blacklist? (empty list will be always flagged as blacklist)
        use-as-blacklist: true
        #worlds of the list
        worlds: []
    display-name:
        autogenerate: true