name: DeepQuests
main: emanondev.quests.Quests
version: 2.2.4-ALPHA
author: emanon
softdepend: [Factions,Towny,SuperVanish,PremiumVanish,Mcmmo,VirginBlock,WorldGuard,PlaceHolderAPI,Citizens,MythicMobs,WorldGuardRegionAPI,Jobs]
api-version: 1.13

commands:
    quests:
        description: reload the config
        usage: "§cUsage: /quests"
        permission: quests.commands.quests
        aliases: [quest,q]
    questsadmin:
        description: reload the config
        usage: "§cUsage: /questadmin"
        aliases: [qa,questadmin,questsadmin,qadmin]
    questtext:
        description: when a string is requested
        usage: "§cUsage: /questtext"
    questitem:
        description: when an item is requested
        usage: "§cUsage: /questitem"
        
permissions:
    quests.admin.help:
        default: op
    quests.admin.reload:
        default: op
    quests.admin.listquest:
        default: op
    quests.admin.quest:
        default: op
    quests.admin.deletequest:
        default: op
    quests.admin.addquest:
        default: op
    quests.admin.editor:
        default: op
    quests.bossbar.seetask:
        default: true
    quests.commands.quests:
        default: true
    quests.gui.seeall:
        default: op
    