name: DeepQuests
main: emanondev.quests.Quests
version: ${project.version}
author: emanon
softdepend: [Factions,Towny,SuperVanish,PremiumVanish,Mcmmo,VirginBlock,WorldGuard,PlaceHolderAPI,Citizens,MythicMobs,WGRegionEvents,Jobs]

commands:
    quests:
        description: reload the config
        usage: "§cUsage: /quests"
        permission: quests.commands.quests
        aliases: [quest]
    questsadmin:
        description: reload the config
        usage: "§cUsage: /questadmin"
        aliases: [qa,questadmin,questsadmin,qadmin]
        
permissions:
    quests.commands.admin.reload:
        default: op
    quests.commands.admin.help:
        default: op
    quests.commands.quests:
        default: true
    