name: DeepQuests
main: emanondev.quests.Quests
version: ${project.version}
author: emanon
softdepend: [Factions,Towny,SuperVanish,PremiumVanish,Mcmmo,VirginBlock,WorldGuard,PlaceHolderAPI,Citizens,MythicMobs,WGRegionEvents,Jobs]

commands:
    quests:
        description: reload the config
        usage: "§cUsage: /quests"
        permission: quests.commands.quests
        aliases: [quest]
    questsadmin:
        description: reload the config
        usage: "§cUsage: /questadmin"
        aliases: [qa,questadmin,questsadmin,qadmin]
        
permissions:
    quests.admin.help:
        default: op
    quests.admin.reload:
        default: op
    quests.admin.listquest:
        default: op
    quests.admin.quest:
        default: op
    quests.admin.quest.listmission:
        default: op
    quests.admin.quest.mission:
        default: op
    quests.admin.quest.mission.info:
        default: op
    quests.admin.deletequest:
        default: op
    quests.admin.addquest:
        default: op
    quests.admin.quest.info:
        default: op
    quests.admin.quest.deletemission:
        default: op
    quests.admin.quest.addmission:
        default: op
    quests.admin.quest.mission.task:
        default: op
    quests.admin.quest.mission.task.info:
        default: op
    quests.admin.editor:
        default: op
        
    quests.commands.quests:
        default: true
    quests.gui.seeall:
        default: op
    